---
# Default variables for Docker installation role

# Docker packages to install
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Required system packages for Docker installation
docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

# Docker service configuration
docker_service_enabled: true
docker_service_state: started

# User configuration
docker_add_user_to_group: true
docker_user: "{{ ansible_user }}"

# Repository configuration
docker_apt_cache_valid_time: 3600